import type { LucideIcon } from 'lucide-react'
import {
  UtensilsCrossed,
  Coffee,
  Pizza,
  Beef,
  Car,
  Bus,
  Plane,
  Fuel,
  Home,
  Lightbulb,
  Wrench,
  Sofa,
  HeartPulse,
  Pill,
  Stethoscope,
  Dumbbell,
  Film,
  Music,
  Gamepad2,
  Tv,
  CreditCard,
  Landmark,
  Banknote,
  ReceiptText,
  Briefcase,
  TrendingUp,
  Coins,
  HandCoins,
  PiggyBank,
  Target,
  Vault,
  LineChart,
  ShoppingCart,
  ShoppingBag,
  Gift,
  Shirt,
  Star,
  Bookmark,
  CircleDot,
  Sparkles,
  Wallet,
  Tag,
} from 'lucide-react'

export const ICON_CATALOG: Record<string, LucideIcon> = {
  UtensilsCrossed,
  Coffee,
  Pizza,
  Beef,
  Car,
  Bus,
  Plane,
  Fuel,
  Home,
  Lightbulb,
  Wrench,
  Sofa,
  HeartPulse,
  Pill,
  Stethoscope,
  Dumbbell,
  Film,
  Music,
  Gamepad2,
  Tv,
  CreditCard,
  Landmark,
  Banknote,
  ReceiptText,
  Briefcase,
  TrendingUp,
  Coins,
  HandCoins,
  PiggyBank,
  Target,
  Vault,
  LineChart,
  ShoppingCart,
  ShoppingBag,
  Gift,
  Shirt,
  Star,
  Bookmark,
  CircleDot,
  Sparkles,
}

export const ICON_GROUPS: Record<string, (keyof typeof ICON_CATALOG)[]> = {
  Comida: ['UtensilsCrossed', 'Coffee', 'Pizza', 'Beef'],
  Transporte: ['Car', 'Bus', 'Plane', 'Fuel'],
  Hogar: ['Home', 'Lightbulb', 'Wrench', 'Sofa'],
  Salud: ['HeartPulse', 'Pill', 'Stethoscope', 'Dumbbell'],
  Entretenimiento: ['Film', 'Music', 'Gamepad2', 'Tv'],
  'Tarjetas / Deuda': ['CreditCard', 'Landmark', 'Banknote', 'ReceiptText'],
  Ingreso: ['Briefcase', 'TrendingUp', 'Coins', 'HandCoins'],
  Ahorro: ['PiggyBank', 'Target', 'Vault', 'LineChart'],
  Compras: ['ShoppingCart', 'ShoppingBag', 'Gift', 'Shirt'],
  Genérico: ['Star', 'Bookmark', 'CircleDot', 'Sparkles'],
}

export const CUENTA_FALLBACK_ICON: LucideIcon = Wallet
export const CATEGORIA_FALLBACK_ICON: LucideIcon = Tag

/** Every render site calls this instead of reimplementing null/unknown-name fallback logic. */
export function resolveIcon(iconName: string | null | undefined, kind: 'cuenta' | 'categoria'): LucideIcon {
  if (iconName && iconName in ICON_CATALOG) return ICON_CATALOG[iconName]
  return kind === 'cuenta' ? CUENTA_FALLBACK_ICON : CATEGORIA_FALLBACK_ICON
}
